defaults:
  - trainer: trainer



training_session_manager:
    _target_: src.training_session_manager.training_starter.TrainingStarter



lightning_module:

  metric_collections:
    val:
      _target_: src.metrics.metric_base.MetricCollection
      metrics:
        forcemetrics:
          _target_: src.metrics.force_metrics.ForceMetrics
          forcing_intervals:
            - 2
            - 5
            - ${forcing_interval} #forcing interval that is used in train
            - 1000000 #Run Model without forcing
        trajectory_plot:
            _target_: src.metrics.trajectory3d.Trajectory3D
            n_time_steps: 100
            n_trajectories: 10
        gradient_plot:
            _target_: src.metrics.gradient_plot3d.GradientPlot3d

    test:
      _target_: src.metrics.metric_base.MetricCollection
      metrics:
        mmd:
          _target_: src.metrics.maximum_mean_discrepancy.GaussianMaximumMeanDiscrepancy
          bandwidth: 0.5
          n_samples: -1
          n_time_steps: -1
        trajectory_plot:
          _target_: src.metrics.trajectory3d.Trajectory3D
        gradient_plot:
          _target_: src.metrics.gradient_plot3d.GradientPlot3d




  hidden_markov_model:


    transition_sampler:
      model:
        _target_: src.models.transition_models.plrnns.final_plrnns.ConstantCovClippedShallowPLRNN
        z_dim: ${z_dim}
        sigma: 1.
        hidden_dim: 100




      distribution:
        _target_: hydra.utils.get_method
        path: pyro.distributions.Normal
      _target_: src.models.model_sampler.ModelBasedSampler
    observation_sampler:
      model:
        _target_: src.models.observation_models.IdentityObservationModel
        obs_dim: ${obs_dim}
      distribution:
        _target_: hydra.utils.get_method
        path: pyro.distributions.Normal
      _target_: src.models.model_sampler.ModelBasedSampler
    initial_sampler:
      _target_: src.models.model_sampler.ModelBasedSampler
      model:
        _target_: src.models.inital_models.SimpleInit
        z_dim: ${z_dim}

      distribution:
        _target_: hydra.utils.get_method
        path: pyro.distributions.Normal


    _target_: src.models.hidden_markov_model.HiddenMarkovModel
  variational_distribution:
    _target_: src.models.guides.TimeSeriesCNN
    input_dim: ${obs_dim}
    output_dim: ${z_dim}
    num_filters: 128
  optimizer:
    _target_: functools.partial
    _args_:
    - _target_: hydra.utils.get_class
      path: torch.optim.RAdam
    lr: 0.01
  loss:
    _target_: src.training.losses.TeacherForcingTraceELBO
    forcing_interval: ${forcing_interval}
    alpha: 0.2
    subspace_dim: 1
  messengers:
    _target_: src.pyro_messengers.annealing_messenger.AnnealingScaleMessenger
    beginning_annealing_factor: 1
    annealing_epochs: 100
    latent_group_name: z
  _target_: src.lightning_modules.variational_lightning_module.LightningVariationalHiddenMarkov
data_module:
  _target_: src.data.data_module.ChunkTimeSeriesDataModule
  dataset:
    _target_: src.data.time_series_dataset.TimeSeriesChunkDataset
    tensors:
      _target_: src.data.data_simulator.data_simulator.DataSimulator.hydra_get_data
      combinations:
      - initial_state:
        - 1
        - 1
        - 1
      drift_function:
        _target_: hydra.utils.get_method
        path: src.data.data_simulator.drift_functions.lorentz_drift
      observation_function:
        _target_: src.data.data_simulator.observation_functions.Downsampler
        n_of_target_points: 512
      initial_state:
      - 1
      - 1
      - 1
    chunk_length: ${chunk_length}
  batch_size: 64


obs_dim: 3
z_dim: 3
chunk_length: 100
forcing_interval: 1
run_id: fc61c6874f934064a5ad53f1166cceac
models_to_reload:
  - hidden_markov_model
  - variational_distribution
#check_point_name: epoch=64-step=4160


hydra:
  searchpath:
    - file://conf
