defaults:
  - default_config
  - _self_
  - override transition_model: shallowPLRNN




z_dim: 30
obs_dim: 19
training:
  n_epochs: 10
  annealing_factor: 0.1
  annealing_epochs: 100
optimizer:
  optim_args:
    lr:
      0.01

transition_model:
  connectivity_module:
    hidden_dim: 10
  cov_module:
    _target_: plrnns.LinearCovariance
loss:
  num_particles: 1
data:
  subject_index: null
  batch_size: 12