defaults:
  - _self_
  - data: data
  - guide: rnn
  - loss: loss
  - observation_model: linear
  - transition_model: dendPLRNN
  - observation_distribution: normal
  - transition_distribution: normal
  - optimizer: adam
  - training: train


z_dim: 5
obs_dim: 19
