defaults:
  - config
  - _self_
  - override transition_model: shallowPLRNN
  - override guide:



z_dim: 1
obs_dim: 19
training:
  n_epochs: 50
  annealing_factor: 0.2
  annealing_epochs: 25
optimizer:
  optim_args:
    lr:
      1.
guide:
  _target_: pyro.infer.autoguide.AutoDiagonalNormal
  model:
    _target_: time_series_model.TimeSeriesModel
    _args_:
      - ${transition_model}
      - ${observation_model}
      - ${observation_distribution}
      - ${transition_distribution}

transition_model:
  connectivity_module:
    hidden_dim: 10
  cov_module:
    _target_: plrnns.LinearCovariance
loss:
  num_particles: 1
