defaults:
  - hidden_markov_model: hmm1
  - variational_distribution: simplenn
  - data_loader: simple_lorentz
  - optimizer: adam
  - loss: force_elbo
  - metric_collection: metric_collections
  - messengers:
      - annealing





_target_: src.lightning_module.LightningVariationalHiddenMarkov
obs_dim: 1
z_dim: 10
