defaults:
  - _self_
  - data: data_module
  - module: annealing_module
  - guide: rnn
  - loss: loss
  - observation_model: linear
  - transition_model: _DendPLRNN
  - observation_distribution: normal
  - transition_distribution: normal
  - optimizer: adam
  - training: train
  - metriccollection: metric_collections


z_dim: 5
obs_dim: 19

