defaults:
  - callbacks:
      - early_stopping
      - model_check_point
  - logger: mlflow_logger


_target_: lightning.pytorch.trainer.trainer.Trainer
enable_checkpointing: true
num_sanity_val_steps: 1
accelerator: cpu
max_epochs: 100
min_epochs: 10
check_val_every_n_epoch: 5
inference_mode: false

#default_root_dir: C:\Users\roman.nefedov\PycharmProjects\PLRNN_Family_Variational_Inference\lightning_logs
