_target_: pyro.infer.autoguide.AutoDiagonalNormal
model:
  _target_: src.models.time_series_model.HiddenMarkovModel
  _args_:
    - ${transition_model}
    - ${observation_model}
    - ${observation_distribution}
    - ${transition_distribution}
init_scale: 0.1