train:
  _target_: src.metrics.force_metrics.ForceMetrics
  forcing_intervals:
    - 2
    - 5
    - ${forcing_interval} #forcing interval that is used in train
    - 1000000 #Run Model without forcing
test:
  _target_: src.metrics.maximum_mean_discrepancy.GaussianMaximumMeanDiscrepancy
  bandwidth: 0.5
  n_samples: -1



