defaults:
  - metrics/force_metrics@metrics.force_metrics
  - metrics/trajectory_plot@metrics.trajectory_plot
  - metrics/gradient_plot@metrics.gradient_plot
  - metrics/plrnn_metric@metrics.plrnn_metric

_target_: src.metrics.metric_base.MetricCollection