_target_: src.models.transition_models.PLRNN
z_dim: ${z_dim}
connectivity_module:
  _target_: src.models.transition_models.DendriticConnector
  z_dim: ${z_dim}
  B: 10
cov_module:
  _target_: src.models.transition_models.ConstantCovariance
  z_dim: ${z_dim}